Error building categorical dataset:
Traceback (most recent call last):
  File "/Users/abelguevarah/Desktop/IA/p2/resources/generate_simulated_dataset.py", line 408, in <module>
    score = node_scores['rendimiento'] + np.random.uniform(-0.5, 0.5, size=N)
            ~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'rendimiento'
